### ISSUE TITLE
front camera

### ISSUE THREAD

**Issue by ggichure** [abdulhaq/SnapchatLikeCamera#5]
the front camera is somehow  unscaled. its elongating one's face.How do i go about fixing these.great project ..

**Comment by abdulhaq** [comment]
In preview or after image is taken? Also which device are you using, different device screen size might be causing this issue.

**Comment by ggichure** [comment]
on prieview.tested it on api 19 and 27.also in the manifest you missed   <uses-permission android:name="android.permission.FLASHLIGHT" />

**Comment by abdulhaq** [comment]
On [line 663](https://github.com/abdulhaq/SnapchatLikeCamera/blob/afd3bc193d4548a18efd94809965d7cedf3a6d47/app/src/main/java/life/haq/it/android/snapchatlikecamera/CameraPreview.java#L663) of CameraPreview.java file is where the size for preview is set. Try playing with '1920' figure to get your desired screen size.

**Comment by ggichure** [comment]
played with it,its working now...however when taking a photo the view is somewhat not propotional like you find face is elongated but on capture its propotional

**Comment by abdulhaq** [comment]
Make the same change on [this ](https://github.com/abdulhaq/SnapchatLikeCamera/blob/afd3bc193d4548a18efd94809965d7cedf3a6d47/app/src/main/java/life/haq/it/android/snapchatlikecamera/CameraPreview.java#L317)line aswell.
